
var posicao= [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];
var conteudo=[0,0,1,1,2,2,3,3,4,4,5,5,6,6,7,7,8,8,9,9];
var estado= [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];
var sorteado;
var acertos=0
for(var x=0;x<20;x++){
    sorteado=Number.parseInt(Math.random()*(20-x));
    posicao[x]=conteudo[sorteado];
    conteudo.splice(sorteado,1);
}
var bgmodal=window.document.getElementById('bgmodal')
var titulo=window.document.getElementById('titulo')

var i=window.document.getElementById('imagem0');
var i0=window.document.getElementById('imagem0');
var i1=window.document.getElementById('imagem1');
var i2=window.document.getElementById('imagem2');
var i3=window.document.getElementById('imagem3');
var i4=window.document.getElementById('imagem4');
var i5=window.document.getElementById('imagem5');
var i6=window.document.getElementById('imagem6');
var i7=window.document.getElementById('imagem7');
var i8=window.document.getElementById('imagem8');
var i9=window.document.getElementById('imagem9');

var i10=window.document.getElementById('imagem10');
var i11=window.document.getElementById('imagem11');
var i12=window.document.getElementById('imagem12');
var i13=window.document.getElementById('imagem13');
var i14=window.document.getElementById('imagem14');
var i15=window.document.getElementById('imagem15');
var i16=window.document.getElementById('imagem16');
var i17=window.document.getElementById('imagem17');
var i18=window.document.getElementById('imagem18');
var i19=window.document.getElementById('imagem19');

i0.addEventListener('click', clicar0);
i1.addEventListener('click', clicar1);
i2.addEventListener('click', clicar2);
i3.addEventListener('click', clicar3);
i4.addEventListener('click', clicar4);
i5.addEventListener('click', clicar5);
i6.addEventListener('click', clicar6);
i7.addEventListener('click', clicar7);
i8.addEventListener('click', clicar8);
i9.addEventListener('click', clicar9);

i10.addEventListener('click', clicar10);
i11.addEventListener('click', clicar11);
i12.addEventListener('click', clicar12);
i13.addEventListener('click', clicar13);
i14.addEventListener('click', clicar14);
i15.addEventListener('click', clicar15);
i16.addEventListener('click', clicar16);
i17.addEventListener('click', clicar17);
i18.addEventListener('click', clicar18);
i19.addEventListener('click', clicar19);

window.setInterval(verificar,4000)
function clicar0(){ 
    verificar()
    if(posicao[0]===0){
        i0.src="imagens/zero.png"
    }else
    if(posicao[0]===1){
        i0.src="imagens/um.png" 
    }else
    if(posicao[0]===2){
        i0.src="imagens/dois.png" 
    }else
    if(posicao[0]===3){
        i0.src="imagens/tres.png" 
    }else
    if(posicao[0]===4){
        i0.src="imagens/quatro.png" 
    }else
    if(posicao[0]===5){
        i0.src="imagens/cinco.png"
    }else
    if(posicao[0]===6){
        i0.src="imagens/seis.png" 
    }else
    if(posicao[0]===7){
        i0.src="imagens/sete.png" 
    }else
    if(posicao[0]===8){
        i0.src="imagens/oito.png" 
    }else
    if(posicao[0]===9){
        i0.src="imagens/nove.png" 
    }
    estado[0]=1
    comparar(0)
}
function clicar1(){
    verificar()
    if(posicao[1]===0){
        i1.src="imagens/zero.png"
    }else
    if(posicao[1]===1){
        i1.src="imagens/um.png" 
    }else
    if(posicao[1]===2){
        i1.src="imagens/dois.png" 
    }else
    if(posicao[1]===3){
        i1.src="imagens/tres.png" 
    }else
    if(posicao[1]===4){
        i1.src="imagens/quatro.png" 
    }else
    if(posicao[1]===5){
        i1.src="imagens/cinco.png"
    }else
    if(posicao[1]===6){
        i1.src="imagens/seis.png" 
    }else
    if(posicao[1]===7){
        i1.src="imagens/sete.png" 
    }else
    if(posicao[1]===8){
        i1.src="imagens/oito.png" 
    }else
    if(posicao[1]===9){
        i1.src="imagens/nove.png" 
    }
    estado[1]=1
    comparar(1)
}
function clicar2(){
    verificar()
    if(posicao[2]===0){
        i2.src="imagens/zero.png"
    }else
    if(posicao[2]===1){
        i2.src="imagens/um.png" 
    }else
    if(posicao[2]===2){
        i2.src="imagens/dois.png" 
    }else
    if(posicao[2]===3){
        i2.src="imagens/tres.png" 
    }else
    if(posicao[2]===4){
        i2.src="imagens/quatro.png" 
    }else
    if(posicao[2]===5){
        i2.src="imagens/cinco.png"
    }else
    if(posicao[2]===6){
        i2.src="imagens/seis.png" 
    }else
    if(posicao[2]===7){
        i2.src="imagens/sete.png" 
    }else
    if(posicao[2]===8){
        i2.src="imagens/oito.png" 
    }else
    if(posicao[2]===9){
        i2.src="imagens/nove.png" 
    }
    estado[2]=1
    comparar(2)
}
function clicar3(){
    verificar()
    if(posicao[3]===0){
        i3.src="imagens/zero.png"
    }else
    if(posicao[3]===1){
        i3.src="imagens/um.png" 
    }else
    if(posicao[3]===2){
        i3.src="imagens/dois.png" 
    }else
    if(posicao[3]===3){
        i3.src="imagens/tres.png" 
    }else
    if(posicao[3]===4){
        i3.src="imagens/quatro.png" 
    }else
    if(posicao[3]===5){
        i3.src="imagens/cinco.png"
    }else
    if(posicao[3]===6){
        i3.src="imagens/seis.png" 
    }else
    if(posicao[3]===7){
        i3.src="imagens/sete.png" 
    }else
    if(posicao[3]===8){
        i3.src="imagens/oito.png" 
    }else
    if(posicao[3]===9){
        i3.src="imagens/nove.png" 
    }
    estado[3]=1;
    comparar(3)
}
function clicar4(){
    verificar()
    if(posicao[4]===0){
        i4.src="imagens/zero.png"
    }else
    if(posicao[4]===1){
        i4.src="imagens/um.png" 
    }else
    if(posicao[4]===2){
        i4.src="imagens/dois.png" 
    }else
    if(posicao[4]===3){
        i4.src="imagens/tres.png" 
    }else
    if(posicao[4]===4){
        i4.src="imagens/quatro.png" 
    }else
    if(posicao[4]===5){
        i4.src="imagens/cinco.png"
    }else
    if(posicao[4]===6){
        i4.src="imagens/seis.png" 
    }else
    if(posicao[4]===7){
        i4.src="imagens/sete.png" 
    }else
    if(posicao[4]===8){
        i4.src="imagens/oito.png" 
    }else
    if(posicao[4]===9){
        i4.src="imagens/nove.png" 
    }
    estado[4]=1
    comparar(4)
}
function clicar5(){
    verificar()
    if(posicao[5]===0){
        i5.src="imagens/zero.png"
    }else
    if(posicao[5]===1){
        i5.src="imagens/um.png" 
    }else
    if(posicao[5]===2){
        i5.src="imagens/dois.png" 
    }else
    if(posicao[5]===3){
        i5.src="imagens/tres.png" 
    }else
    if(posicao[5]===4){
        i5.src="imagens/quatro.png" 
    }else
    if(posicao[5]===5){
        i5.src="imagens/cinco.png"
    }else
    if(posicao[5]===6){
        i5.src="imagens/seis.png" 
    }else
    if(posicao[5]===7){
        i5.src="imagens/sete.png" 
    }else
    if(posicao[5]===8){
        i5.src="imagens/oito.png" 
    }else
    if(posicao[5]===9){
        i5.src="imagens/nove.png" 
    }
    estado[5]=1;
    comparar(5);
}
function clicar6(){
    verificar()
    if(posicao[6]===0){
        i6.src="imagens/zero.png"
    }else
    if(posicao[6]===1){
        i6.src="imagens/um.png" 
    }else
    if(posicao[6]===2){
        i6.src="imagens/dois.png" 
    }else
    if(posicao[6]===3){
        i6.src="imagens/tres.png" 
    }else
    if(posicao[6]===4){
        i6.src="imagens/quatro.png" 
    }else
    if(posicao[6]===5){
        i6.src="imagens/cinco.png"
    }else
    if(posicao[6]===6){
        i6.src="imagens/seis.png" 
    }else
    if(posicao[6]===7){
        i6.src="imagens/sete.png" 
    }else
    if(posicao[6]===8){
        i6.src="imagens/oito.png" 
    }else
    if(posicao[6]===9){
        i6.src="imagens/nove.png" 
    }
    estado[6]=1;
    comparar(6);
}
function clicar7(){
    verificar()
    if(posicao[7]===0){
        i7.src="imagens/zero.png"
    }else
    if(posicao[7]===1){
        i7.src="imagens/um.png" 
    }else
    if(posicao[7]===2){
        i7.src="imagens/dois.png" 
    }else
    if(posicao[7]===3){
        i7.src="imagens/tres.png" 
    }else
    if(posicao[7]===4){
        i7.src="imagens/quatro.png" 
    }else
    if(posicao[7]===5){
        i7.src="imagens/cinco.png"
    }else
    if(posicao[7]===6){
        i7.src="imagens/seis.png" 
    }else
    if(posicao[7]===7){
        i7.src="imagens/sete.png" 
    }else
    if(posicao[7]===8){
        i7.src="imagens/oito.png" 
    }else
    if(posicao[7]===9){
        i7.src="imagens/nove.png" 
    }
    estado[7]=1;
    comparar(7);
}
function clicar8(){
    verificar()
    if(posicao[8]===0){
        i8.src="imagens/zero.png"
    }else
    if(posicao[8]===1){
        i8.src="imagens/um.png" 
    }else
    if(posicao[8]===2){
        i8.src="imagens/dois.png" 
    }else
    if(posicao[8]===3){
        i8.src="imagens/tres.png" 
    }else
    if(posicao[8]===4){
        i8.src="imagens/quatro.png" 
    }else
    if(posicao[8]===5){
        i8.src="imagens/cinco.png"
    }else
    if(posicao[8]===6){
        i8.src="imagens/seis.png" 
    }else
    if(posicao[8]===7){
        i8.src="imagens/sete.png" 
    }else
    if(posicao[8]===8){
        i8.src="imagens/oito.png" 
    }else
    if(posicao[8]===9){
        i8.src="imagens/nove.png" 
    }
    estado[8]=1;
    comparar(8);
}
function clicar9(){
    verificar()
    if(posicao[9]===0){
        i9.src="imagens/zero.png"
    }else
    if(posicao[9]===1){
        i9.src="imagens/um.png" 
    }else
    if(posicao[9]===2){
        i9.src="imagens/dois.png" 
    }else
    if(posicao[9]===3){
        i9.src="imagens/tres.png" 
    }else
    if(posicao[9]===4){
        i9.src="imagens/quatro.png" 
    }else
    if(posicao[9]===5){
        i9.src="imagens/cinco.png"
    }else
    if(posicao[9]===6){
        i9.src="imagens/seis.png" 
    }else
    if(posicao[9]===7){
        i9.src="imagens/sete.png" 
    }else
    if(posicao[9]===8){
        i9.src="imagens/oito.png" 
    }else
    if(posicao[9]===9){
        i9.src="imagens/nove.png" 
    }
    estado[9]=1;
    comparar(9);
    
}
function clicar10(){ 
    verificar()
    if(posicao[10]===0){
        i10.src="imagens/zero.png"
    }else
    if(posicao[10]===1){
        i10.src="imagens/um.png" 
    }else
    if(posicao[10]===2){
        i10.src="imagens/dois.png" 
    }else
    if(posicao[10]===3){
        i10.src="imagens/tres.png" 
    }else
    if(posicao[10]===4){
        i10.src="imagens/quatro.png" 
    }else
    if(posicao[10]===5){
        i10.src="imagens/cinco.png"
    }else
    if(posicao[10]===6){
        i10.src="imagens/seis.png" 
    }else
    if(posicao[10]===7){
        i10.src="imagens/sete.png" 
    }else
    if(posicao[10]===8){
        i10.src="imagens/oito.png" 
    }else
    if(posicao[10]===9){
        i10.src="imagens/nove.png" 
    }
    estado[10]=1
    comparar(10)
}
function clicar11(){ 
    verificar()
    if(posicao[11]===0){
        i11.src="imagens/zero.png"
    }else
    if(posicao[11]===1){
        i11.src="imagens/um.png" 
    }else
    if(posicao[11]===2){
        i11.src="imagens/dois.png" 
    }else
    if(posicao[11]===3){
        i11.src="imagens/tres.png" 
    }else
    if(posicao[11]===4){
        i11.src="imagens/quatro.png" 
    }else
    if(posicao[11]===5){
        i11.src="imagens/cinco.png"
    }else
    if(posicao[11]===6){
        i11.src="imagens/seis.png" 
    }else
    if(posicao[11]===7){
        i11.src="imagens/sete.png" 
    }else
    if(posicao[11]===8){
        i11.src="imagens/oito.png" 
    }else
    if(posicao[11]===9){
        i11.src="imagens/nove.png" 
    }
    estado[11]=1
    comparar(11)
}
function clicar12(){ 
    verificar()
    if(posicao[12]===0){
        i12.src="imagens/zero.png"
    }else
    if(posicao[12]===1){
        i12.src="imagens/um.png" 
    }else
    if(posicao[12]===2){
        i12.src="imagens/dois.png" 
    }else
    if(posicao[12]===3){
        i12.src="imagens/tres.png" 
    }else
    if(posicao[12]===4){
        i12.src="imagens/quatro.png" 
    }else
    if(posicao[12]===5){
        i12.src="imagens/cinco.png"
    }else
    if(posicao[12]===6){
        i12.src="imagens/seis.png" 
    }else
    if(posicao[12]===7){
        i12.src="imagens/sete.png" 
    }else
    if(posicao[12]===8){
        i12.src="imagens/oito.png" 
    }else
    if(posicao[12]===9){
        i12.src="imagens/nove.png" 
    }
    estado[12]=1
    comparar(12)
}
function clicar13(){ 
    verificar()
    if(posicao[13]===0){
        i13.src="imagens/zero.png"
    }else
    if(posicao[13]===1){
        i13.src="imagens/um.png" 
    }else
    if(posicao[13]===2){
        i13.src="imagens/dois.png" 
    }else
    if(posicao[13]===3){
        i13.src="imagens/tres.png" 
    }else
    if(posicao[13]===4){
        i13.src="imagens/quatro.png" 
    }else
    if(posicao[13]===5){
        i13.src="imagens/cinco.png"
    }else
    if(posicao[13]===6){
        i13.src="imagens/seis.png" 
    }else
    if(posicao[13]===7){
        i13.src="imagens/sete.png" 
    }else
    if(posicao[13]===8){
        i13.src="imagens/oito.png" 
    }else
    if(posicao[13]===9){
        i13.src="imagens/nove.png" 
    }
    estado[13]=1
    comparar(13)
}
function clicar14(){ 
    verificar()
    if(posicao[14]===0){
        i14.src="imagens/zero.png"
    }else
    if(posicao[14]===1){
        i14.src="imagens/um.png" 
    }else
    if(posicao[14]===2){
        i14.src="imagens/dois.png" 
    }else
    if(posicao[14]===3){
        i14.src="imagens/tres.png" 
    }else
    if(posicao[14]===4){
        i14.src="imagens/quatro.png" 
    }else
    if(posicao[14]===5){
        i14.src="imagens/cinco.png"
    }else
    if(posicao[14]===6){
        i14.src="imagens/seis.png" 
    }else
    if(posicao[14]===7){
        i14.src="imagens/sete.png" 
    }else
    if(posicao[14]===8){
        i14.src="imagens/oito.png" 
    }else
    if(posicao[14]===9){
        i14.src="imagens/nove.png" 
    }
    estado[14]=1
    comparar(14)
}
function clicar15(){ 
    verificar()
    if(posicao[15]===0){
        i15.src="imagens/zero.png"
    }else
    if(posicao[15]===1){
        i15.src="imagens/um.png" 
    }else
    if(posicao[15]===2){
        i15.src="imagens/dois.png" 
    }else
    if(posicao[15]===3){
        i15.src="imagens/tres.png" 
    }else
    if(posicao[15]===4){
        i15.src="imagens/quatro.png" 
    }else
    if(posicao[15]===5){
        i15.src="imagens/cinco.png"
    }else
    if(posicao[15]===6){
        i15.src="imagens/seis.png" 
    }else
    if(posicao[15]===7){
        i15.src="imagens/sete.png" 
    }else
    if(posicao[15]===8){
        i15.src="imagens/oito.png" 
    }else
    if(posicao[15]===9){
        i15.src="imagens/nove.png" 
    }
    estado[15]=1
    comparar(15)
}
function clicar16(){ 
    verificar()
    if(posicao[16]===0){
        i16.src="imagens/zero.png"
    }else
    if(posicao[16]===1){
        i16.src="imagens/um.png" 
    }else
    if(posicao[16]===2){
        i16.src="imagens/dois.png" 
    }else
    if(posicao[16]===3){
        i16.src="imagens/tres.png" 
    }else
    if(posicao[16]===4){
        i16.src="imagens/quatro.png" 
    }else
    if(posicao[16]===5){
        i16.src="imagens/cinco.png"
    }else
    if(posicao[16]===6){
        i16.src="imagens/seis.png" 
    }else
    if(posicao[16]===7){
        i16.src="imagens/sete.png" 
    }else
    if(posicao[16]===8){
        i16.src="imagens/oito.png" 
    }else
    if(posicao[16]===9){
        i16.src="imagens/nove.png" 
    }
    estado[16]=1
    comparar(16)
}
function clicar17(){ 
    verificar()
    if(posicao[17]===0){
        i17.src="imagens/zero.png"
    }else
    if(posicao[17]===1){
        i17.src="imagens/um.png" 
    }else
    if(posicao[17]===2){
        i17.src="imagens/dois.png" 
    }else
    if(posicao[17]===3){
        i17.src="imagens/tres.png" 
    }else
    if(posicao[17]===4){
        i17.src="imagens/quatro.png" 
    }else
    if(posicao[17]===5){
        i17.src="imagens/cinco.png"
    }else
    if(posicao[17]===6){
        i17.src="imagens/seis.png" 
    }else
    if(posicao[17]===7){
        i17.src="imagens/sete.png" 
    }else
    if(posicao[17]===8){
        i17.src="imagens/oito.png" 
    }else
    if(posicao[17]===9){
        i17.src="imagens/nove.png" 
    }
    estado[17]=1
    comparar(17)
}
function clicar18(){ 
    verificar()
    if(posicao[18]===0){
        i18.src="imagens/zero.png"
    }else
    if(posicao[18]===1){
        i18.src="imagens/um.png" 
    }else
    if(posicao[18]===2){
        i18.src="imagens/dois.png" 
    }else
    if(posicao[18]===3){
        i18.src="imagens/tres.png" 
    }else
    if(posicao[18]===4){
        i18.src="imagens/quatro.png" 
    }else
    if(posicao[18]===5){
        i18.src="imagens/cinco.png"
    }else
    if(posicao[18]===6){
        i18.src="imagens/seis.png" 
    }else
    if(posicao[18]===7){
        i18.src="imagens/sete.png" 
    }else
    if(posicao[18]===8){
        i18.src="imagens/oito.png" 
    }else
    if(posicao[18]===9){
        i18.src="imagens/nove.png" 
    }
    estado[18]=1
    comparar(18)
}
function clicar19(){ 
    verificar()
    if(posicao[19]===0){
        i19.src="imagens/zero.png"
    }else
    if(posicao[19]===1){
        i19.src="imagens/um.png" 
    }else
    if(posicao[19]===2){
        i19.src="imagens/dois.png" 
    }else
    if(posicao[19]===3){
        i19.src="imagens/tres.png" 
    }else
    if(posicao[19]===4){
        i19.src="imagens/quatro.png" 
    }else
    if(posicao[19]===5){
        i19.src="imagens/cinco.png"
    }else
    if(posicao[19]===6){
        i19.src="imagens/seis.png" 
    }else
    if(posicao[19]===7){
        i19.src="imagens/sete.png" 
    }else
    if(posicao[19]===8){
        i19.src="imagens/oito.png" 
    }else
    if(posicao[19]===9){
        i19.src="imagens/nove.png" 
    }
    estado[19]=1
    comparar(19)
}

function comparar(atual){
    for(var x=0;x<20;x++){
        if(estado[x]===1 && estado[atual]===1 && x!=atual && posicao[x]===posicao[atual]){
            if(x===0){
               i0.removeEventListener('click',clicar0)
                estado[x]=0  
            }else
            if(x===1){
               i1.removeEventListener('click',clicar1)
                estado[x]=0
            }else
            if(x===2){
                i2.removeEventListener('click',clicar2)
                estado[x]=0  
            }else
            if(x===3){
                i3.removeEventListener('click',clicar3)
                estado[x]=0 
            }else
            if(x===4){
                i4.removeEventListener('click',clicar4)
                estado[x]=0 
            }else
            if(x===5){
                i5.removeEventListener('click',clicar5)
                estado[x]=0 
            }else
            if(x===6){
                i6.removeEventListener('click',clicar6)
                estado[x]=0 
            }else
            if(x===7){
                i7.removeEventListener('click',clicar7)
                estado[x]=0 
            }else
            if(x===8){
                i8.removeEventListener('click',clicar8)
                estado[x]=0 
            }else
            if(x===9){
                i9.removeEventListener('click',clicar9)
                estado[x]=0 
            }else                   //Décima
            if(x===10){
                i10.removeEventListener('click',clicar10)
                 estado[x]=0  
             }else
             if(x===11){
                i11.removeEventListener('click',clicar11)
                 estado[x]=0
             }else
             if(x===12){
                 i12.removeEventListener('click',clicar12)
                 estado[x]=0  
             }else
             if(x===13){
                 i13.removeEventListener('click',clicar13)
                 estado[x]=0 
             }else
             if(x===14){
                 i14.removeEventListener('click',clicar14)
                 estado[x]=0 
             }else
             if(x===15){
                 i15.removeEventListener('click',clicar15)
                 estado[x]=0 
             }else
             if(x===16){
                 i16.removeEventListener('click',clicar16)
                 estado[x]=0 
             }else
             if(x===17){
                 i17.removeEventListener('click',clicar17)
                 estado[x]=0 
             }else
             if(x===18){
                 i18.removeEventListener('click',clicar18)
                 estado[x]=0 
             }else
             if(x===19){
                 i19.removeEventListener('click',clicar19)
                 estado[x]=0 
             }

            //Atual
            if(atual===0){
                i0.removeEventListener('click',clicar0)
                estado[atual]=0 
                acertos+=1 
            }else
            if(atual===1){
                i1.removeEventListener('click',clicar1)
                estado[atual]=0 
                acertos+=1 
            }else
            if(atual===2){
                i2.removeEventListener('click',clicar2)
                estado[atual]=0 
                acertos+=1 
            }else
            if(atual===3){
                i3.removeEventListener('click',clicar3)
                estado[atual]=0 
                acertos+=1 
            }else
            if(atual===4){
                i4.removeEventListener('click',clicar4)
                estado[atual]=0 
                acertos+=1 
            }else
            if(atual===5){
                i5.removeEventListener('click',clicar5)
                estado[atual]=0 
                acertos+=1 
            }else
            if(atual===6){
                i6.removeEventListener('click',clicar6)
                estado[atual]=0 
                acertos+=1 
            }else
            if(atual===7){
                i7.removeEventListener('click',clicar7)
                estado[atual]=0 
                acertos+=1 
            }else
            if(atual===8){
                i8.removeEventListener('click',clicar8)
                estado[atual]=0 
                acertos+=1 
            }else
            if(atual===9){
                i9.removeEventListener('click',clicar9)
                estado[atual]=0 
                acertos+=1 
            }else                    //Décima
            if(atual===10){
                i10.removeEventListener('click',clicar10)
                estado[atual]=0 
                acertos+=1 
            }else
            if(atual===11){
                i11.removeEventListener('click',clicar11)
                estado[atual]=0 
                acertos+=1 
            }else
            if(atual===12){
                i12.removeEventListener('click',clicar12)
                estado[atual]=0 
                acertos+=1 
            }else
            if(atual===13){
                i13.removeEventListener('click',clicar13)
                estado[atual]=0 
                acertos+=1 
            }else
            if(atual===14){
                i14.removeEventListener('click',clicar14)
                estado[atual]=0 
                acertos+=1 
            }else
            if(atual===15){
                i15.removeEventListener('click',clicar15)
                estado[atual]=0 
                acertos+=1 
            }else
            if(atual===16){
                i16.removeEventListener('click',clicar16)
                estado[atual]=0 
                acertos+=1 
            }else
            if(atual===17){
                i17.removeEventListener('click',clicar17)
                estado[atual]=0 
                acertos+=1 
            }else
            if(atual===18){
                i18.removeEventListener('click',clicar18)
                estado[atual]=0 
                acertos+=1 
            }else
            if(atual===19){
                i19.removeEventListener('click',clicar19)
                estado[atual]=0 
                acertos+=1 
            }        
        }
    }
    
    if(acertos==10){
        bgmodal.style.display='block'
        titulo.style.textAlign='center'
    }    
} 
function verificar(){
    for(var x=0;x<20;x++){
        for(var y=0;y<20;y++){
            if(estado[x]===1 && estado[y]===1 && x!=y && posicao[x]!=posicao[y]){
                       
                viraXY(x,y)                                      
            }    
        }
         
    }
    
}
function viraXY(a,b){
    viraX(a)
    viraY(b)
}
function viraX(x){
    if(x===0){
        i0.src="imagens/numeros.jpg"
        estado[x]=0
    }else
    if(x===1){
        i1.src="imagens/numeros.jpg"
        estado[x]=0
    }else
    if(x===2){
        i2.src="imagens/numeros.jpg"
        estado[x]=0
    }else
    if(x===3){
        i3.src="imagens/numeros.jpg"
        estado[x]=0
    }else
    if(x===4){
        i4.src="imagens/numeros.jpg"
        estado[x]=0
    }else
    if(x===5){
        i5.src="imagens/numeros.jpg"
        estado[x]=0
    }else
    if(x===6){
        i6.src="imagens/numeros.jpg"
        estado[x]=0
    }else
    if(x===7){
        i7.src="imagens/numeros.jpg"
        estado[x]=0
    }else
    if(x===8){
        i8.src="imagens/numeros.jpg"
        estado[x]=0
    }else
    if(x===9){
        i9.src="imagens/numeros.jpg"
        estado[x]=0
    }else                 //Décima
    if(x===10){
        i10.src="imagens/numeros.jpg"
        estado[x]=0
    }else
    if(x===11){
        i11.src="imagens/numeros.jpg"
        estado[x]=0
    }else
    if(x===12){
        i12.src="imagens/numeros.jpg"
        estado[x]=0
    }else
    if(x===13){
        i13.src="imagens/numeros.jpg"
        estado[x]=0
    }else
    if(x===14){
        i14.src="imagens/numeros.jpg"
        estado[x]=0
    }else
    if(x===15){
        i15.src="imagens/numeros.jpg"
        estado[x]=0
    }else
    if(x===16){
        i16.src="imagens/numeros.jpg"
        estado[x]=0
    }else
    if(x===17){
        i17.src="imagens/numeros.jpg"
        estado[x]=0
    }else
    if(x===18){
        i18.src="imagens/numeros.jpg"
        estado[x]=0
    }else
    if(x===19){
        i19.src="imagens/numeros.jpg"
        estado[x]=0
    }             
}
function viraY(y){
    if(y===0){
        i0.src="imagens/numeros.jpg"
        estado[y]=0 
    }else
    if(y===1){
        i1.src="imagens/numeros.jpg"
        estado[y]=0 
    }else                        
    if(y===2){
        i2.src="imagens/numeros.jpg"
        estado[y]=0 
    }else
    if(y===3){
        i3.src="imagens/numeros.jpg"
        estado[y]=0 
    }else
    if(y===4){
        i4.src="imagens/numeros.jpg"
        estado[y]=0 
    }else
    if(y===5){
        i5.src="imagens/numeros.jpg"
        estado[y]=0 
    }else
    if(y===6){
        i6.src="imagens/numeros.jpg"
        estado[y]=0 
    }else
    if(y===7){
        i7.src="imagens/numeros.jpg"
        estado[y]=0 
    }else
    if(y===8){
        i8.src="imagens/numeros.jpg"
        estado[y]=0 
    }else
    if(y===9){
        i9.src="imagens/numeros.jpg"
        estado[y]=0 
    }else               //Décima
    if(y===10){
        i10.src="imagens/numeros.jpg"
        estado[y]=0 
    }else
    if(y===11){
        i11.src="imagens/numeros.jpg"
        estado[y]=0 
    }else                        
    if(y===12){
        i12.src="imagens/numeros.jpg"
        estado[y]=0 
    }else
    if(y===13){
        i13.src="imagens/numeros.jpg"
        estado[y]=0 
    }else
    if(y===14){
        i14.src="imagens/numeros.jpg"
        estado[y]=0 
    }else
    if(y===15){
        i15.src="imagens/numeros.jpg"
        estado[y]=0 
    }else
    if(y===16){
        i16.src="imagens/numeros.jpg"
        estado[y]=0 
    }else
    if(y===17){
        i17.src="imagens/numeros.jpg"
        estado[y]=0 
    }else
    if(y===18){
        i18.src="imagens/numeros.jpg"
        estado[y]=0 
    }else
    if(y===19){
        i19.src="imagens/numeros.jpg"
        estado[y]=0 
    }
}
